// Generated by CoffeeScript 1.4.0
(function() {

  describe("Max Power Function", function() {
    return describe("When A is 4 and B is 9", function() {
      return it("it should return 7", function() {
        return expect(Math.MaxPowerFunc(4, 9)).toBe(7);
      });
    });
  });

}).call(this);
