// Generated by CoffeeScript 1.4.0
(function() {
  var MaxPowerResult;

  Math.MaxPowerFunc = function(A, B) {
    var result;
    result = Math.MaxPowerAlgorithm(10, A, B);
    return result.max;
  };

  MaxPowerResult = (function() {

    function MaxPowerResult(value, max) {
      this.value = value;
      this.max = max;
    }

    return MaxPowerResult;

  })();

  Math.MaxPowerAlgorithm = function(N, A, B) {
    var result;
    if (N === 0) {
      return new MaxPowerResult(1, 1);
    }
    result = Math.MaxPowerAlgorithm(N - 1, A, B);
    result.value = (A * result.value) % B;
    result.max = Math.max(result.value, result.max);
    return result;
  };

}).call(this);
